# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      # Compile and run test
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      # Store the jar generated as an actifact
      - name: Update actifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/**/*.jar
        
  cd:
    runs-on: ubuntu-latest
    
    # This job depends ci job
    needs: ci
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v2
        
      # Download the artifact generated previously
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: target
      
      # Build de docker image and push it to dockerhub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}